@extends('admin.layouts.app')
@section('title', $fashionCollection->exists ? 'Ubah Koleksi Fashion' : 'Tambah Koleksi Fashion')
@section('content')
<div class="heading"><div><h1>{{ $fashionCollection->exists ? 'Ubah Koleksi Fashion' : 'Tambah Koleksi Fashion' }}</h1><p>Semua kolom wajib sesuai instruksi UAS dan akan divalidasi oleh Laravel.</p></div></div>
@include('admin.partials.errors')
<div class="card"><div class="card-body"><form method="POST" enctype="multipart/form-data" action="{{ $fashionCollection->exists ? route('admin.fashion-collections.update', $fashionCollection) : route('admin.fashion-collections.store') }}">@csrf @if($fashionCollection->exists)@method('PUT')@endif
<div class="form-grid"><div class="field"><label for="id_fashion">ID Fashion</label><input id="id_fashion" name="id_fashion" value="{{ old('id_fashion', $fashionCollection->id_fashion) }}" maxlength="30" required></div><div class="field"><label for="nama_item">Nama Item</label><input id="nama_item" name="nama_item" value="{{ old('nama_item', $fashionCollection->nama_item) }}" maxlength="150" required></div><div class="field"><label for="ukuran">Ukuran</label><input id="ukuran" name="ukuran" value="{{ old('ukuran', $fashionCollection->ukuran) }}" maxlength="40" required></div><div class="field"><label for="warna">Warna</label><input id="warna" name="warna" value="{{ old('warna', $fashionCollection->warna) }}" maxlength="80" required></div><div class="field"><label for="brand">Brand</label><input id="brand" name="brand" value="{{ old('brand', $fashionCollection->brand) }}" maxlength="120" required></div><div class="field"><label for="gambar">Gambar {{ $fashionCollection->exists ? '(kosongkan jika tidak diganti)' : '' }}</label><input id="gambar" type="file" name="gambar" accept="image/jpeg,image/png,image/webp" {{ $fashionCollection->exists ? '' : 'required' }}>@if($fashionCollection->gambar)<img class="preview" src="{{ str_starts_with($fashionCollection->gambar, 'images/') ? asset($fashionCollection->gambar) : asset('storage/'.$fashionCollection->gambar) }}" alt="{{ $fashionCollection->nama_item }}">@endif</div></div>
<div class="form-actions"><button class="btn" type="submit">Simpan Koleksi Fashion</button><a class="btn light" href="{{ route('admin.fashion-collections.index') }}">Batal</a></div></form></div></div>
@endsection
